---
name: CD Latest

on:
  push:
    branches:
      - develop

env:
  REGISTRY: ghcr.io

permissions:
  packages: write

jobs:
  CD:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Artefacts
        run: |
          make build
          find azure-servicebus-sink-connector -type f

      - name: Build and Push Image for Multiple Architectures
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          context: .
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}:latest
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=A Kafka Connect Sink Connecter for Azure Service Bus.
