---
name: CI Trivy Scan

on:
  pull_request:
    branches:
      - develop

env:
  ACTIONS_RUNTIME_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-scan:
    name: Build and Scan
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # Build the Docker image
      - name: Build Docker image
        run: |
          make build

      # Run Trivy security scan
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: kc-connectors:latest
          trivy-config: trivy.yaml
